### ISSUE TITLE
2.14.0-beta

### ISSUE THREAD

**Issue by fastepic** [EpicCash/epic#19]
After try epic-wallet check using epic server I have after a few correct receive data error in connection with server - always on the same index ( looks like end of database ). Did other users have the same ? I use linux. Maybe we need one more block mined to have correct possible to check wallet ? I do check and restore after full delete subfolders db and saved_tx  and only old seed file. It is only problem with 2.14 because when I try the same procedure with old 2.13 working server on not rollback chain all  check and restore works correct. No error logs in debug mode (toml) in epic-server.log

`20210330 22:12:47.504 WARN epic_wallet_libwallet::internal::restore - Checking 1000 outputs, up to index 1245529. (Highest index: 1214415)
20210330 22:12:47.504 WARN epic_wallet_libwallet::internal::restore - Scanning 1000 outputs in the current Epic utxo set
20210330 22:12:47.960 ERROR epic_wallet_impls::node_clients::http - get_outputs_by_pmmr_index: error contacting http://localhost:3413. Error: ResponseError error: Cannot parse response
20210330 22:12:47.960 ERROR epic_wallet_controller::command - Wallet check failed: Restore Error
20210330 22:12:47.960 ERROR epic_wallet_controller::command - Backtrace: 
Wallet command failed: LibWallet Error: Restore Error`

**Comment by johanneshahn** [comment]
still relevant?

**Comment by JualnSilva** [comment]
As we currently have new versions of Epic and due to the lack of contact we are closing this issue.

If the problem persists in newer versions, please contact us.

I believe this check function has been changed almost completely in the latest version since [3.0.0-alpha-1](https://github.com/EpicCash/epic/releases/tag/debian%2F3.0.0-alpha-1) to [3.0.0-alpha-4](https://github.com/EpicCash/epic/releases/tag/debian%2F3.0.0-alpha-4). These changes are already present in the most current version 3.0.0 present on the [epic.tech](https://epic.tech/downloads/) website.
